### ISSUE TITLE
Audio/Video/ADB

### ISSUE THREAD

**Issue by YevheniL** [GloDroid/glodroid_manifest#10]
Hello, could you please answer on few questions:
1) How to connect by adb via usb wire? For now when i plug it i can not see any activity. And command adb devices returning empty result. 
2) What happen with video playing ? In the first your release it is worked, but for now not. How to return this possibility?

**Comment by rsglobal** [comment]
Hi,

ADB should work. Youtube video in webview browser should also work. 
Which release and board are you using?
Are you using prebuilt image or compile from scratch?

**Comment by YevheniL** [comment]
In Youtube it is working fine, video from the folder directory not. 
For now i using the last one version from this repository.
ADB via Ethernet or via USB ? 
I had error on the device Failed to get adbd socket, No such file or directory. 
Thank you very match for the fast answer !

**Comment by YevheniL** [comment]
It is write, that i am not superuser, that`s why adb is stopped.

**Comment by rsglobal** [comment]
To make adb / fastboot work without sudo you have to install adb package:
```sudo apt install adb```

Video playback issue is tracked in #13
