### ISSUE TITLE
Could I use this to flash GrapheneOS to the pinephone?

### ISSUE THREAD

**Issue by Frick-David** [GloDroid/glodroid_manifest#109]
Could anyone help me do this? I would be super stocked to make some documentation on this!

**Comment by squidink7** [comment]
I tried to flash a GSI on mine but it didn't have enough space even after deleting the product partition. I'm not an expert on android so I don't know how to make more space for it although it might be possible to switch out AOSP for another android ROM like graphene

**Comment by qwertyisabelle** [comment]
Can the pine phone even run grapheneos? I thought grapheneos needed hardware security things like titan m and such that the pine phone just doesn’t have.

**Comment by Frick-David** [comment]
Yes, it probably can not be flashed. Closing
