### ISSUE TITLE
fastboot not recognising pinephone

### ISSUE THREAD

**Issue by squidink7** [GloDroid/glodroid_manifest#114]
I've successfully flashed deploy-sd.img but it boots to a black screen with the LED on. When I run flash-sd.sh it says waiting for device and stops there. I've also tried flashing the old v0.2 iso and then running adb reboot bootloader, which worked but fastboot still doesn't recognise the device. It's appearing in Plasma as pinephone however, and adb commands all work just not fastboot.

**Comment by squidink7** [comment]
Fixed it by running as root

**Comment by EnfrigFalco** [comment]
Same issue. Using Fedora 34 and android-tools. Phone has red dot. Fedora shows "waiting for any device". Tried with and without root. Tried re-flashing sd-card as GPT and MBR, tried deploy-sd, deploy-sd-for-emmch, and deploy-gpt. Using latest 'balena etcher' for flashing.
