### ISSUE TITLE
Request to support Libre Tritium H3 board

### ISSUE THREAD

**Issue by keiem** [GloDroid/glodroid_manifest#115]
Hello,

would it be difficult to support the Libre Tritium H3 board?

**Comment by rsglobal** [comment]
Hi, I suspect initial bring-up should be trivial.

**Comment by keiem** [comment]
Thank! Is it the same as in linux systems, changing dtb and u-boot?

**Comment by rsglobal** [comment]
You can use device/glodroid/opi_plus2e as reference and change dts/defconfigs for your board.
