### ISSUE TITLE
Shutdown Raspberry Pi

### ISSUE THREAD

**Issue by squidink7** [GloDroid/glodroid_manifest#118]
How do you shutdown the raspberry pi? there is no power button and unplugging the cord doesn't seem to be good for it.

**Comment by rsglobal** [comment]
You will need to adjust dts / overlay and map some of GPIO as a key: https://www.kernel.org/doc/Documentation/devicetree/bindings/input/gpio-keys.txt

Event number should be:
https://github.com/torvalds/linux/blob/48342fc07272eec454fc5b400ed3ce3739c7e950/include/uapi/linux/input-event-codes.h#L191
