### ISSUE TITLE
next branch of device repo cannot match master branch of this repo

### ISSUE THREAD

**Issue by Icenowy** [glodroid/glodroid_manifest#12]
The next branch of the device repo has already landed PinePhone support, which needed rtl8723cs that is only available in this repo at next branch.

**Comment by rsglobal** [comment]
@Icenowy ,

I haven't found  way how to inherit project branch from the manifest branch.
After we setup CI to check PR, we can drop next->master flow and use only master.
Sorry for inconvenience.
I need more time to test all recent changes. Then I'll update master and put tags for next release.

**Comment by rsglobal** [comment]
master branch has been updated with next
