### ISSUE TITLE
Cant build image for opi_pc

### ISSUE THREAD

**Issue by tmpdo** [GloDroid/glodroid_manifest#132]
it will stop at java optimizations:
user@ETALONDEB10:~/buid/GloDroid$ make 
17:41:59 Build sandboxing disabled due to nsjail error.
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
TARGET_PRODUCT=opi_pc
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.19.0-14-amd64-x86_64-Debian-GNU/Linux-10-(buster)
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=RP1A.200720.011
OUT_DIR=out
============================================
[  0% 1/425] profile boot jars
FAILED: out/soong/opi_pc/dex_bootjars/boot.prof
ANDROID_LOG_TAGS="*:e" out/soong/host/linux-x86/bin/profman --create-profile-from=frameworks/base/config/boot-image-profile.txt --apk=out/soong/opi_pc/dex_artjars_input/core-oj.jar --apk=out/soong/opi_pc/dex_artjars_input/core-libart.jar --apk=out/soong/opi_pc/dex_artjars_input/core-icu4j.jar --apk=out/soong/opi_pc/dex_artjars_input/okhttp.jar --apk=out/soong/opi_pc/dex_artjars_input/bouncycastle.jar --apk=out/soong/opi_pc/dex_artjars_input/apache-xml.jar --apk=out/soong/opi_pc/dex_bootjars_input/framework.jar --apk=out/soong/opi_pc/dex_bootjars_input/ext.jar --apk=out/soong/opi_pc/dex_bootjars_input/telephony-common.jar --apk=out/soong/opi_pc/dex_bootjars_input/voip-common.jar --apk=out/soong/opi_pc/dex_bootjars_input/ims-common.jar --apk=out/soong/opi_pc/dex_bootjars_input/framework-atb-backward-compatibility.jar --dex-location=/apex/com.android.art/javalib/core-oj.jar --dex-location=/apex/com.android.art/javalib/core-libart.jar --dex-location=/apex/com.android.art/javalib/core-icu4j.jar --dex-location=/apex/com.android.art/javalib/okhttp.jar --dex-location=/apex/com.android.art/javalib/bouncycastle.jar --dex-location=/apex/com.android.art/javalib/apache-xml.jar --dex-location=/system/framework/framework.jar --dex-location=/system/framework/ext.jar --dex-location=/system/framework/telephony-common.jar --dex-location=/system/framework/voip-common.jar --dex-location=/system/framework/ims-common.jar --dex-location=/system/framework/framework-atb-backward-compatibility.jar --reference-profile-file=out/soong/opi_pc/dex_bootjars/boot.prof
Illegal instruction
17:42:23 ninja failed with: exit status 1

**Comment by rsglobal** [comment]
The issue is somewhere in your environment.
Please try again using docker, see more info at https://github.com/GloDroid/glodroid_manifest/commit/88009f78d3f514550c8795d76e20acc30dcd1377
