### ISSUE TITLE
ETA for next build?

### ISSUE THREAD

**Issue by squidink7** [GloDroid/glodroid_manifest#133]
Theres a bunch of new features for the pinephone that is only available in the next branch. I just tried to build it but ran out of storage on my machine, so rather than torture my poor SSD any more I thought I'd ask when the next build is being shipped? I'm really looking forward to seeing a build containing the features in the next branch.

**Comment by rsglobal** [comment]
Hi.

Release is almost ready and needs testing before publishing.
You can access the latest build here: https://github.com/rsglobal/glodroid_manifest/releases/tag/v0.6.0-validation

**Comment by rsglobal** [comment]
Please use #58  for such kind of requests.
