### ISSUE TITLE
Create docker container and the manual to allow building on wide range of distros

### ISSUE THREAD

**Issue by rsglobal** [GloDroid/glodroid_manifest#135]
This aims to solve build issues reported by some of the users.

Example:
https://github.com/islem19/AOSP-Build-on-Docker

**Comment by neonfuz** [comment]
I am currently building using a docker image. When I have time (next few days) I'll clean it up and publish it.

**Comment by rsglobal** [comment]
Awesome, thanks!

**Comment by rsglobal** [comment]
Dockerfile was added by https://github.com/GloDroid/glodroid_manifest/pull/136  
The manual is available in the pull request description.
