### ISSUE TITLE
audio jack switching not working on pinephone

### ISSUE THREAD

**Issue by squidink7** [GloDroid/glodroid_manifest#138]
the pinephone has had some issues with switching to the headphones automatically when plugged in, but using the latest 5.12 kernel on Manjaro this has been fixed. I noticed in the 0.6.1 builds this isn't working yet it's still running linux 5.12. Would you know why that may be?

**Comment by rsglobal** [comment]
As far as I know plug/unplug events are successfully translated to Android framework. What is missing is configuration sets for routing audio in this file https://github.com/GloDroid/glodroid_device/blob/13504605aedb8bebcbbe9b95dba5c292686888db/pinephone/audio.pinephone.xml

**Comment by rsglobal** [comment]
From Linux side it usually implemented by alsa-ucm-conf: Example for different hardware: https://github.com/Srinivas-Kandagatla/alsa-ucm-conf/commit/c84edaf5afaaea45d0347863d7f868b3a95de915

**Comment by rsglobal** [comment]
#143 should address this issue.

**Comment by madriemx** [comment]
Should this issue be reopened now, while #143 wasn't sufficient?

**Comment by QushyQushy** [comment]
This issue should be reopened, it's the only thing not working apart from the camera.

**Comment by IMSOASIAN** [comment]
I second this, auto jack switching is not working on my PinePhone either.

**Comment by herbsmn** [comment]
I just tested this on v0.8.1 with the pinephone and it is still an issue. Please reopen this issue.

**Comment by herbsmn** [comment]
Would updating the glodroid tinyhal fork potentially help? It doesn't seem to have been updated since September 2020: https://github.com/GloDroid/glodroid_forks/tree/tinyhal-next

It looks like it is regularly updated here: https://github.com/CirrusLogic/tinyhal

**Comment by rsglobal** [comment]
Fixed in 2023w16 release: https://github.com/GloDroidCommunity/pine64-pinephone/releases/tag/2023w16
