### ISSUE TITLE
pinephone: whats the status on modem support?

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [GloDroid/glodroid_manifest#144]
I know that it's not working at the moment, but at what point do you think it'll be introduced?

**Comment by EnderNightLord-ChromeBook** [comment]
All I know is that you can't use Networkmanager or ofono.

**Comment by rsglobal** [comment]
Modem is not supported now. There are some plans, but I can't promise any ETA.

**Comment by EnderNightLord-ChromeBook** [comment]
Thank you
