### ISSUE TITLE
auto mount USB storage

### ISSUE THREAD

**Issue by danialbehzadi** [GloDroid/glodroid_manifest#146]
I'm currently using my build of GloDroid on Raspberry Pi 4. But nothing happens when I attach a USB storage device to my rpi4. I think that should be mounted automatically.

**Comment by danialbehzadi** [comment]
Just checked that [konstakang kernel](https://github.com/lineage-rpi/android_kernel_brcm_rpi) auto mounts USB storages too.

**Comment by rsglobal** [comment]
@KonstaT ,

Thanks, added to fstab as you suggested. Seems to work.
Fix will be available in v0.7.0.
