### ISSUE TITLE
Opi3 write sdcard

### ISSUE THREAD

**Issue by cyber-bat** [GloDroid/glodroid_manifest#154]
I wrote deploy-sd. img to the sdcard, all the partitions were created, including those with boot.scr, but opi3 is not loaded from the sdcard.  Please help me to fix it.

**Comment by rsglobal** [comment]
Sorry, I probably missed this issue. After you start the board, it will enter fastboot mode, you have to continue flashing by running flash script. Please refer to our manual for more info: https://github.com/GloDroid/glodroid_manifest#deploying-glodroid
