### ISSUE TITLE
[GSM][OPTIONAL] Radio module initialization hardening

### ISSUE THREAD

**Issue by matviizorin** [GloDroid/glodroid_manifest#157]
We should finalize the RIL integration to finally fix initialization issues. The output of ` adb logcat -b radio` has been attached.

[logcat_radio_init.log](https://github.com/GloDroid/glodroid_manifest/files/7224240/logcat_radio_init.log)

**Comment by rsglobal** [comment]
Brand new radio HAL available:
https://github.com/GloDroid/mm-radio
All modem-related issues should go there.
