### ISSUE TITLE
[GSM][FEATURE] USSD implementation

### ISSUE THREAD

**Issue by matviizorin** [GloDroid/glodroid_manifest#158]
USSD codes don't work as of now. GSM module should support quick codes to provide mobile operator info. Log after code enter has been attached although RIL should be debugged more accurately for this feature.

[logcat_radio_ussd.log](https://github.com/GloDroid/glodroid_manifest/files/7224331/logcat_radio_ussd.log)

**Comment by rsglobal** [comment]
Brand new radio HAL available:
https://github.com/GloDroid/mm-radio
USSD is working at the moment.
