### ISSUE TITLE
[GSM][FEATURE] Cellular call implementation

### ISSUE THREAD

**Issue by matviizorin** [GloDroid/glodroid_manifest#159]
Cellular call ability is the main feature of GSM module integration. Radio module provides the same default debug information as it is for https://github.com/GloDroid/glodroid_manifest/issues/158.

[logcat_radio_call.log](https://github.com/GloDroid/glodroid_manifest/files/7224393/logcat_radio_call.log)

**Comment by rsglobal** [comment]
it works more or less on v0.7.1, so I will close this.
