### ISSUE TITLE
Default Password?

### ISSUE THREAD

**Issue by Csanderson03** [GloDroid/glodroid_manifest#167]
Hey, What is the default password that its asking for to get log in on the phone?

Thank You so much
Chris

**Comment by rsglobal** [comment]
Hi,

GloDroid doesn't have any passwords

**Comment by Csanderson0313** [comment]
Oh wait, I know why. It's not actually loading on my SD card. Why does it say not a bootable image when loading?
Thank you

**Comment by rsglobal** [comment]
Could you provide more info on your system, what is happening and what is expected to happen. Attach some logs if possible.

**Comment by Csanderson0313** [comment]
I will go and download GloDroid 6.1. I will use balena etcher to Flash it on my SD card. When I select the file to flat, a pop up saying "missing partition table" (see attached picture).
![20211113_083316](https://user-images.githubusercontent.com/59343494/141646045-3898e4bc-0690-435e-86c3-a8cba4085492.jpg)

![20211113_083334](https://user-images.githubusercontent.com/59343494/141646061-a9b2ba5a-e413-4bc3-859f-8282e4663fdb.jpg)
 
Thank you

**Comment by rsglobal** [comment]
You have to unpack it first.

**Comment by Csanderson0313** [comment]
I did unzip the file and doing the same thing. What unzip program are you using? Maybe it's the unzip software that I'm using that causing issues.

**Comment by rsglobal** [comment]
Please refer to README.md file for instructions or search for installation guidelines on youtube.
