### ISSUE TITLE
Build using /e/OS manifest! - Feature Request

### ISSUE THREAD

**Issue by erikd256** [GloDroid/glodroid_manifest#173]
Would you like to try out this?

https://gitlab.e.foundation/pinephone/

It is /e/OS, which is waaaay better than AOSP. Maybe you could provide also an /e/OS image on top of the AOSP image still being offered as option?

**Comment by rsglobal** [comment]
Hi,

AOSP is the mainline while lineage/e. are forks.
Our mission is to create foss vendor images. Mission of e. Is to somehow customize system/product images.

In the end we want to be gsi compatible, therefore lineage/e/other custom forks can mix their system/product images with glodroid vendor image/platform images.

Also looks like /e/ does blame Google for spying, while we are trying to collaborate with Google (upstreaming to AOSP is an important part of our activities)
Therefore combine both e and glodroid here isn't a good idea for our progress.
