### ISSUE TITLE
Letting skytube be uninstallable

### ISSUE THREAD

**Issue by squidink7** [GloDroid/glodroid_manifest#176]
Currently skytube, which is installed by default on GloDroid, can't be uninstalled, only disabled. Other system apps such as shade launcher and firefox can be uninstalled, however skytube cannot. It would be appreciated if this was changed, as while its nice to have, its not necessary for android to function, and the space could be used for other applications or data, or just to keep a clean system.

**Comment by rsglobal** [comment]
Sounds reasonable. Will do.

**Comment by rsglobal** [comment]
Change is available in `next` branch. Will be shipped in the next pre-release.
