### ISSUE TITLE
Please add support for Librem 5

### ISSUE THREAD

**Issue by andrew712-1** [GloDroid/glodroid_manifest#179]
Thank you.

**Comment by rsglobal** [comment]
Hmmmm. iMX SOC. I always wanted this chip in GloDroid devices family.

**Comment by rsglobal** [comment]
1200 USD per piece, what the... huge price...?

**Comment by andrew712-1** [comment]
It has started at $599

https://tuxphones.com/purism-librem-5-2021-2022-price-increase/

**Comment by rsglobal** [comment]
Pinephone pro has more advanced hardware and cost only 399usd which is also high, comparing to aliexpress pixel3 for 150usd.

**Comment by rsglobal** [comment]
Sorry, we do not have enough engineering resources to support this device near future.
