### ISSUE TITLE
Guidance for adding old qcom-based devices

### ISSUE THREAD

**Issue by vknecht** [GloDroid/glodroid_manifest#180]
Hi !
I'd like using GloDroid for building recent Android for msm8916/msm8939 devices,
(namely msm8916-alcatel-idol347 and msm8939-alcatel-idol3) which already have
decent close-to-mainline kernel support for postmarketOS.

Where should they be added in the directory hierarchy ?
```device/qcom/alcatel-idol347/``` or ```device/qcom/idol347/```, or something else ?

What about potentially shared qcom-related configs ?
I see ```device/linaro/dragonboard/``` has some, which may be reused for some parts,
but also things like ```rmtfs``` which don't have some mod I got in upstream.
Should that be duplicated ?

Any tips how to set up kernel and what to use for HALs would be welcome since I only have
limited knowledge of Android bringup (only rebuilt and tweaked old LOS port for them)...

**Comment by rsglobal** [comment]
Looks like no one here have experience with qualcomm.
