### ISSUE TITLE
adb not working on next branch

### ISSUE THREAD

**Issue by SimoneFrau** [GloDroid/glodroid_manifest#181]
Hi, I updated my build with last changes from next branch but I noticed adb is not available anymore.
Do you maybe have a quick fix I can apply?

Thank you for your support and the great work!

Simone

**Comment by rsglobal** [comment]
Hi,

What is your device?

**Comment by SimoneFrau** [comment]
Hi, my device is an Rpi4

**Comment by rsglobal** [comment]
Hm... It works for me.

**Comment by rsglobal** [comment]
Looks like it's another force-pushed tag issue.

**Comment by rsglobal** [comment]
Anyway, next isn't in a good shape. Please wait for v0.7.1
