### ISSUE TITLE
OrangePi 3 LTS videos from youtube crashing webview (firefox and other browsers) 

### ISSUE THREAD

**Issue by Sekilsgs2** [GloDroid/glodroid_manifest#191]
crashes when watching a youtube video

logcat - 
https://pastebin.com/ziqp0R0J

**Comment by rsglobal** [comment]
Hi,

I can't see anything suspicious in logcat , is it complete?
Please try updating external/mesa3d to v0.7.2 and check again

**Comment by Sekilsgs2** [comment]
> Hi,
> 
> I can't see anything suspicious in logcat , is it complete? Please try updating external/mesa3d to v0.7.2 and check again

Full logcat - https://www.filemail.com/d/kgkgasuqbtjdrfd

Ok  -i'm trying latest 0.7.2 variants..

What about panvk (vulkan panfrost) - this have working state? maybe using vulkan for ui? or this never working for us?

**Comment by rsglobal** [comment]
Vulkan require adding some features to mesa3d. It doesn't work now for Android. UI on vulkan will require adding even more features to mesa3d.

**Comment by rsglobal** [comment]
I've been watching youtube on opi3 @ v0.7.2 for an hour. I suspect it's an issue related to opi-lts.

**Comment by Sekilsgs2** [comment]
Yes on 0.7.2 - working thank.

And one moment - 

I'm have lcd hdmi 10 inch 1280x800 - in edid have two modes - with 60hz and with 15 hz - why abdroid by default change to 15hz mode and i'm have very bad fps for all system. To fix this i'm edit system display service and refuse modes which have < 25 hz refresh rate.. But maybe android have settings for hdmi modes and need activate this ?

**Comment by rsglobal** [comment]
I'll look into it. Thanks.
