### ISSUE TITLE
GloDroid v0.7.4 on PinePhone v1.2: autorotate doesn't work

### ISSUE THREAD

**Issue by volkertb** [GloDroid/glodroid_manifest#196]
See my complete list of test findings (with some extra info) in this discussion: https://github.com/GloDroid/glodroid_manifest/discussions/195

**Comment by rsglobal** [comment]
Thanks a lot for your feedback. Looks like I forgot to bump iio-sensors to v0.7.4 before release. Will be fixed in v0.7.5.

**Comment by rsglobal** [comment]
Fixed in v0.7.5
