### ISSUE TITLE
Network (at least WiFi) support for Raspberry PI 400 device...

### ISSUE THREAD

**Issue by DORNINEM** [GloDroid/glodroid_manifest#205]
I did not spent much time but it seems that the wifi adapter builtin the Raspberry PI400 did not work ;(.  It seems slightly the same as for the Raspberry PI4B... Any idea to debug and check if it's a driver issue or another thing ? Regards Emmanuel

**Comment by rsglobal** [comment]
WIFI should have been always working. Anyway, please check if the latest release work for you. https://github.com/GloDroidCommunity/raspberry-pi/releases
