### ISSUE TITLE
Raspberry Pi4 flash-sd.sh is fail for user mode.

### ISSUE THREAD

**Issue by Tonyaplex2017** [GloDroid/glodroid_manifest#208]
Hello ,
I am trying to modify GloDroid v0.5.0 (android 11)  ,change userdebug to user mode , when I use the flash-sd.sh to flash raspberry pi4 ,always got error as below. GloDroid can support user mode? 

Sending 'dtbo_a' (48 KB)                           OKAY [  0.003s]
Writing 'dtbo_a'                                   FAILED (remote: 'No such file or directory')
fastboot: error: Command failed

**Comment by rsglobal** [comment]
Hello,

User builds enforces selinux checks, therefore you have to add missing selinux rules.
