### ISSUE TITLE
The app works well in debug mode, but not in release mode

### ISSUE THREAD

**Issue by ram-1997** [GloDroid/glodroid_manifest#212]
App working well in debug mode but  when we run in release mode some image show but not UI part showing without any error
![this is the UI we want but only background image showing in release mode](https://user-images.githubusercontent.com/108860644/183847051-09985d97-b62a-4671-9bf3-48de7dd7a43e.jpeg)

//=======

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2 21D49 darwin-x64, locale
    en-IN)
    • Flutter version 3.0.5 at /Users/sandeepkumar/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/sandeepkumar/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/sandeepkumar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.68.1)
    • VS Code at /Users/sandeepkumar/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2 21D49 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by nguyenanhgiau** [comment]
Hi guy,
How could you build the variant rpi4-user?

**Comment by rsglobal** [comment]
This issue is likely related to the app or GLES renderer, not the platform. I'm afraid we won't be able to help you.

But if you still believe it's a glodroid issue, feel free to reopen the issue, providing at least logcat output.
