### ISSUE TITLE
[Pinephone Pro] Many problems after flash V0.8.0

### ISSUE THREAD

**Issue by candymannetje** [GloDroid/glodroid_manifest#216]
I just installed Glodroid V0.8.0 on my pinephone pro.
But there are many problems.
1. No sound with calls.
2. Camera not working.
3. Telegram doesn't open after install. 

When boot I get a message:
There's an internal problem with your device.
Contact your manufacturer for details.

**Comment by rsglobal** [comment]
Thanks for sharing your testing results. Those issues are known and tracked at https://github.com/GloDroidCommunity/pine64-pinephonepro/issues/1.
The PPP repository has been moved to https://github.com/GloDroidCommunity/pine64-pinephonepro/
