### ISSUE TITLE
Device "broken" after "upgrading" to v.0.8.0

### ISSUE THREAD

**Issue by IMSOASIAN** [GloDroid/glodroid_manifest#217]
*Hello there,*

I know that this is probably not the proper place to put this, but this is the only avenue I can utilize. The official AOSP mailing lists state that I cannot expect help for other distributions, and the discord link does not work for me.

### **Debug log: Attached [here](https://gist.github.com/IMSOASIAN/df506d4a55173b77b9aaddc9b1f77df0)**

I "upgraded" my GloDroid version, but since I didn't want to lose any data, I followed the advice of #82. However, whenever I now start up my PinePhone a prompt comes up that says;

"There's an internal problem with your device. Contact your manufacturer for details.".

After looking up this issue online, I think the problem may be that some versions of files are not up-to-date, and the files flashed from the v.0.8.0 image mark them as broken.

Can someone help me find a fix for this?

Thanks,

-[T] IMSOASIAN (For some reason the prebuilt for PinePhone still has the serial console enabled??)

**Comment by rsglobal** [comment]
The GloDroid doesn't guarantee a smooth update without losing data. At least now. Maybe later, we will support some OTA,
