### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by minsvc** [GloDroid/glodroid_manifest#218]
FAILED: including vendor/opengapps/build/modules/ActionsServices/Android.mk ...
Error: makefile error
Output:
ziparchive W 09-01 08:52:20   186   186] Unable to open '': No such file or directory
zipinfo: couldn't open : I/O error
tools/tradefederation/prebuilts/test_harness/Android.mk: error: ActionsServices: No source files specified 
In file included from tools/tradefederation/prebuilts/test_harness/Android.mk:52:
In file included from vendor/opengapps/build/modules/ActionsServices/Android.mk:8:
In file included from vendor/opengapps/build/core/prebuilt_apk.mk:61:
In file included from build/make/core/prebuilt.mk:26:
build/make/core/prebuilt_internal.mk:37: error: done.

**Comment by rsglobal** [comment]
GloDroid doesn't include opengapps, we can't help you with that.
