### ISSUE TITLE
Note: Support Matrix for PinePhone Pro

### ISSUE THREAD

**Issue by hamishmb** [GloDroid/glodroid_manifest#221]
As discussed on the Discord server, here's a feature Matrix of what is known to work on the PinePhone Pro. I don't (yet) have one, so I can't do any testing myself yet. Eventually, there'll probably be some wiki pages for this.

- Screen: Working
- GPU (graphics acceleration): OpenGL ES Working, Vulkan Not Working.
- Calls: Not working.
- SMS: Not working.
- 2G data networks: Not working.
- 3G/HSPA: Not working.
- 4G/LTE: Not working.
- Wi-Fi: Should be working, needs confirmation.
- USB-C: Should work in v0.8.1 (not released yet)
- Front-Facing Camera: Not working
- Rear Camera: Not working
- Accelerometer: Working
- Gyroscope: Working
- Other sensors: Unknown
- Waydroid: Working, no GPU acceleration

I'm sure there are omissions in this list. Please comment below with test results and the version of Glodroid you're running so I can add them to the list.

**Comment by hamishmb** [comment]
Note, assuming cameras don't work due to https://github.com/GloDroid/glodroid_manifest/issues/220

**Comment by rsglobal** [comment]
GPU GLES - works
GPU Vulkan - NO
Sensors - accel, gyro - works
Modem (ALL) - NO
WLAN should work
USBC should work in v0.8.1 (not released yet)

**Comment by hamishmb** [comment]
Thanks, updated.

**Comment by rsglobal** [comment]
Support matrix for the PPP moved here: https://github.com/GloDroidCommunity/pine64-pinephonepro/issues/1
