### ISSUE TITLE
modify the default 1024x768 resolution

### ISSUE THREAD

**Issue by minsvc** [GloDroid/glodroid_manifest#225]
### Discussed in https://github.com/GloDroid/glodroid_manifest/discussions/224

<div type='discussions-op-text'>

<sup>Originally posted by **minsvc** September 19, 2022</sup>
I 'm runing glodroid on rpi4.i want to use vnc to connect to the android with custom resolution like 1260*931。the question is how to compile glodroid with custom resolution? please help me,thanks a lot.</div>

**Comment by rsglobal** [comment]
In case you meant headless mode resolution, it can be changed here: https://gitlab.freedesktop.org/drm-hwcomposer/drm-hwcomposer/-/blob/7ee6a9ea6b6873742b7716517f1be18ce39a7524/hwc2_device/HwcDisplayConfigs.cpp#L28

Located at `external/drm_hwcomposer` directory

**Comment by rsglobal** [comment]
`adb shell wm size 1260x931` should work as well.

**Comment by minsvc** [comment]
it works!.thanks.
