### ISSUE TITLE
[Pinephone] Microphone doesn't work

### ISSUE THREAD

**Issue by herbsmn** [GloDroid/glodroid_manifest#229]
I don't have a SIM card to test whether the microphone works on voice calls, which has been reported by others to work, but I can report that the mic on my Pinephone doesn't work in Signal, Conversations, or in any of the voice recorder apps I've downloaded. I'm running v0.8.1.

**Comment by herbsmn** [comment]
Feel free to close this issue since it is addressed in https://github.com/GloDroidCommunity/pine64-pinephone/issues/2

I just tried the newest LineageOS release and the microphone still doesn't seem to be working.

**Comment by rsglobal** [comment]
Fixed in 2023w16 release: https://github.com/GloDroidCommunity/pine64-pinephone/releases/tag/2023w16
