### ISSUE TITLE
Next branch is no longer viewable

### ISSUE THREAD

**Issue by herbsmn** [GloDroid/glodroid_manifest#233]
After previous releases it was possible to view a Next branch to see what is being worked on, but after this last release there is no longer Next branches which are viewable in a number of the repos, including the manifest repo here. I'm not sure if this was intentional or not, but figured I'd submit this issue in case that was done by accident.

**Comment by rsglobal** [comment]
Here is it: https://github.com/GloDroid/glodroid_manifest/pull/232/commits
