### ISSUE TITLE
Unable to flash pinephone with latest glodroid

### ISSUE THREAD

**Issue by h-n-a** [GloDroid/glodroid_manifest#234]
Tried to install the latest glodroid release but it fails right at the bootloader menu and when i try to enter to fastboot mode
This was done using the ./flash-sd.sh method

![IMG_20230211_014049](https://user-images.githubusercontent.com/126036770/221445331-202d0829-592c-49f4-b5c2-cb94f448dde0.jpg)
![IMG_20230211_013831](https://user-images.githubusercontent.com/126036770/221445332-10e6801f-d64a-4d07-bc8c-d7b41632ebb5.jpg)

**Comment by herbsmn** [comment]
I had a similar issue with the last release. I was able to get it to work by using the flash emmc method instead of the flash sd method. Any chance you'd be willing to try that out and see if it works for you?

**Comment by h-n-a** [comment]
@herbsmn thanks for reaching out, yeah i'll try it later today or tomorrow and let you know.

**Comment by rsglobal** [comment]
Please check this PR: https://github.com/GloDroidCommunity/pine64-pinephone/pull/11
(there's a test image link in the first comment)

If the issue is still relevant, please open another issue [HERE](https://github.com/GloDroidCommunity/pine64-pinephone/)
