### ISSUE TITLE
Orange Pi PC

### ISSUE THREAD

**Issue by tantaliom1985** [GloDroid/glodroid_manifest#3]
h if we want to use this for orange pi what we have to do ?

**Comment by rsglobal** [comment]
Orange PI PC is 1GB board and require additional tuning.  
We plan to provide support for 1GB boards in next pre-release.

**Comment by rsglobal** [comment]
Implemented in v0.2.0: https://github.com/GloDroid/glodroid_manifest/releases/tag/v0.2.0
