### ISSUE TITLE
PINEPHONE: Auto rotate inverted

### ISSUE THREAD

**Issue by nas00** [GloDroid/glodroid_manifest#30]
On the latest pinephone release, the screen auto rotates apps to the opposite direction of the physical orientation.

**Comment by rsglobal** [comment]
It seems that X and Y coordinates of accelerometer are swapped. 
https://developer.android.com/guide/topics/sensors/sensors_overview#sensors-coords

**Comment by rsglobal** [comment]
I've added correct mount matrix into pinephone.dtsi that fixed this issue for me.
```
		mount-matrix = "0", "-1", "0",
			       "1", "0", "0",
			       "0", "0", "1";
```

**Comment by rsglobal** [comment]
Change is available in the next integration build:
https://github.com/GloDroid/glodroid_manifest/issues/58#issuecomment-670354906

**Comment by rsglobal** [comment]
IOS orientation: https://developer.apple.com/documentation/uikit/uiacceleration?language=objc
