### ISSUE TITLE
PINEPHONE: Pulsing display

### ISSUE THREAD

**Issue by nas00** [GloDroid/glodroid_manifest#34]
The screen constantly pulses below approx 60% brightness. Pulsing becomes more noticeable as brightness is reduced to minimum.

**Comment by dewitpj** [comment]
I think I saw this on an earlier version - I now have a "band of white" on my display - images to follow

**Comment by nas00** [comment]
I haven't seen whites bands - it's more like a flicker as if the refresh rate is wrong. Seen similar issue on early linux releases.

**Comment by rakor** [comment]
Here too. The screen is flickering and all hard contrasts have like vertical shadows. So a white box in the middle of the screen gives light lines to the top and the bottom of the screen.

**Comment by rsglobal** [comment]
This patch describes something similar:
https://lore.kernel.org/patchwork/patch/1267690/

I still waiting for device, so I can't check now.

**Comment by nas00** [comment]
I've seen the bluetooth issue on debian - every input with bt device caused brightness to increase momentarily. The issue here is a faster flicker - I suppose could be related to the wifi so maybe flipping the relevant kill switches would confirm?

**Comment by rsglobal** [comment]
I've reduced wifi voltage to 1.8:
Can anybody check it
https://drive.google.com/file/d/1MqHAg_g9Jm_5vI2RLtByuKy3_tncvkY7/view?usp=sharing
?

**Comment by dewitpj** [comment]
Downloading - will advise

**Comment by dewitpj** [comment]
I still have the white bars, no flicker as yet

**Comment by rsglobal** [comment]
@dewitpj ,
Can you attach a picture here of the bars?

**Comment by dewitpj** [comment]
Sorry, I did forget to do that:



It’s only when a white screen is present on a dark background 

Thanks!

**Comment by dewitpj** [comment]
Seems email attachments don't work :(

![IMG_1908](https://user-images.githubusercontent.com/17187660/87588914-8dd71300-c738-11ea-940a-9af4d903d9fc.jpg)

**Comment by nas00** [comment]
> I've reduced wifi voltage to 1.8:
> Can anybody check it
> 

It didn't work but it reminded of this display voltage issue:

https://mobile.twitter.com/RealDanct12/status/1232456700868710400

**Comment by anibyl** [comment]
I'm experiencing the same issue.

The temporary "fix" I'm using: brightness ~50% + dark theme.

**Comment by nas00** [comment]
Are those white bars present in other OSes? They look a bit like LCD hardware issues reported by a few owners.

> Seems email attachments don't work :(
>

**Comment by dewitpj** [comment]
> Are those white bars present in other OSes? They look a bit like LCD hardware issues reported by a few owners.
> 
> > Seems email attachments don't work :(

Nope, no lines on other OSs :(

**Comment by anibyl** [comment]
> Nope, no lines on other OSs :(

Can confirm, these are the lines from bright elements on the screen, like icons and buttons.

**Comment by Exonip** [comment]
> > Nope, no lines on other OSs :(
> 
> Can confirm, these are the lines from bright elements on the screen, like icons and buttons.

Can confirm aswell. Any updated yet?

**Comment by rsglobal** [comment]
This and many other hardware issues solved by @megous in his kernel v5.8 integration branch. (https://github.com/megous/linux/tree/orange-pi-5.8)
Currently we are integrating in into the GloDroid.

**Comment by rsglobal** [comment]
Please test if this issue is fixed:
https://github.com/GloDroid/glodroid_manifest/issues/58#issuecomment-670354906
