### ISSUE TITLE
PINEPHONE: Wifi connection unstable

### ISSUE THREAD

**Issue by nas00** [GloDroid/glodroid_manifest#36]
Frequent disconnects and/or very slow connection if no clear line of sight to router, especially when battery not full. Experienced same issue on linux distro when wifi driver was changed for one with hotspot support.

**Comment by rsglobal** [comment]
Please test if this issue is fixed:
https://github.com/GloDroid/glodroid_manifest/issues/58#issuecomment-670354906

**Comment by nas00** [comment]
No more disconnects now. Speed could be faster but in line with other distros. Closing.
