### ISSUE TITLE
lunch opi_plus2e-userdebug

### ISSUE THREAD

**Issue by tantaliom1985** [glodroid/glodroid_manifest#4]
build/make/core/product_config.mk:223: error: Can not locate config makefile for product "opi_plus2e".
05:58:41 dumpvars failed with: exit status 1

**Comment by rsglobal** [comment]
There is a mistake in manual. You have to use `orangepi_plus2e-userdebug` instead.
I expect to release next preview in nearest time where this mistake will be fixed.

**Comment by rsglobal** [comment]
master branch updated. Issue should be fixed.
