### ISSUE TITLE
WiFi Aware Support

### ISSUE THREAD

**Issue by mbalex99** [GloDroid/glodroid_manifest#40]
Hi,

I'm quite interested in this project but I was wondering:

1. Is there WiFi Aware https://www.wi-fi.org/discover-wi-fi/wi-fi-aware support? 
2. If no, how could we contribute to add WiFi Aware Support especially for the Pi -type of phones?

Max

**Comment by rsglobal** [comment]
Hello Max,

Currently there is no support for wifi-aware.

According to:
https://source.android.com/devices/tech/connect/wifi-aware

It would require WiFi HAL, that is missing for PP an other sunxi devices out of the box.

Regards,
Roman

**Comment by rsglobal** [comment]
There is some implementation for WIFI HAL for Broadcom
https://android.googlesource.com/platform/hardware/broadcom/wlan/+/refs/heads/master/bcmdhd/wifi_hal/

So you can try luck to bring it on RPI4 first.

**Comment by rsglobal** [comment]
closing as stale
