### ISSUE TITLE
how big is platform/tools/tradefederation?

### ISSUE THREAD

**Issue by Tarcaxoxide** [GloDroid/glodroid_manifest#45]
been waiting for a pretty long time on 
"Fetching projects:  98% (754/763) platform/tools/tradefederation".
how big is it?

**Comment by rsglobal** [comment]
```
:~/test/GloDroid/tools$ du -hs tradefederation
18M	tradefederation
```

**Comment by rsglobal** [comment]
Try single-thread mode : `repo sync -j1 -c`
Logs will be more accurate then.
