### ISSUE TITLE
PINEPHONE: Adapt libcamera HAL

### ISSUE THREAD

**Issue by rsglobal** [GloDroid/glodroid_manifest#59]
libcamera aims to become the main universal camera HAL for AOSP near future:
https://libcamera.org/docs.html#android-camera-hal

Detailed description/motivation from authors:
https://www.youtube.com/watch?v=S04jOKWHWOg
https://www.youtube.com/watch?v=FovurKj28rw

Unfortunately there is no Android.bp/mk exists. Only meason.

**Comment by rsglobal** [comment]
https://github.com/CoasiaNexell/android_hal_camera/tree/pie-work
Can be also used as reference

**Comment by rsglobal** [comment]
More camera HAL which is working for lineage-rpi.
https://osdn.net/projects/android-x86/scm/git/hardware-libcamera/tree/pie-x86/

**Comment by rsglobal** [comment]
This HAL seems to be mainline and supported:
https://libcamera.org/docs.html#android-camera-hal

Unfortunately there is no Android.bp/mk exists. Only meason.

**Comment by kbingham** [comment]
Indeed we don't yet have an Android blueprint in libcamera, and Android do not support meson or external builds.

We discussed this at the recent Linux plumbers conference, but solutions for integrating meson are not coming soon.

If you construct your own bp integration for Android, the src/android later in libcamera should be already usable, however you might have to add an entry to the simple pipeline handler to support the pinephone.

**Comment by rsglobal** [comment]
@kbingham ,

Hi,
Thank you for your help.
I'm just wondering, how do you testing it with Android? Are you building it using NDK?

**Comment by rsglobal** [comment]
Initial version available:
https://github.com/kbingham/libcamera/pull/26

**Comment by rsglobal** [comment]
Some progress has been done, more info available at : https://github.com/kbingham/libcamera/issues/28

**Comment by rsglobal** [comment]
This is already done in GloDroid, but kernel drivers require a few improvements to make it work. See https://github.com/kbingham/libcamera/issues/28 for more info.
