### ISSUE TITLE
Orange Pi3 build

### ISSUE THREAD

**Issue by AndriiZ** [GloDroid/glodroid_manifest#6]
Can I build Android 10 for OPi3? Looks like latest linux kernel contains almost all required drivers

**Comment by rsglobal** [comment]
We plan t extend this project to cover OPI3, RPI4 in near future.

**Comment by rsglobal** [comment]
Basic bring-up is done on next branch.

**Comment by rich1111** [comment]
Hi, I've build next branch for OPI3, after booting into Android, it say "To start Android, enter your password", What's it?

**Comment by rich1111** [comment]
Hi, I've pass through running on OPI3 the next branch build, but it fail to startup Luncher3.

**Comment by rsglobal** [comment]
Implemented in v0.2.0: https://github.com/GloDroid/glodroid_manifest/releases/tag/v0.2.0
