### ISSUE TITLE
Error checking out repo during sync

### ISSUE THREAD

**Issue by davepo** [GloDroid/glodroid_manifest#69]
I keep getting this error during the 'repo sync -cq' process:

Aborting
error: prebuilts/ndk/: platform/prebuilts/ndk checkout 258d9d2fa15758c968856e92a6c18908bd841697 
error: Cannot checkout platform/prebuilts/ndk

I am unsure if this is something relative to me or a greater issue with sync setup and/or actual repo.

**Comment by davepo** [comment]
Just realized I only posted half of the error message:

Aborting
error: prebuilts/ndk/: platform/prebuilts/ndk checkout 258d9d2fa15758c968856e92a6c18908bd841697 
error: Cannot checkout platform/prebuilts/ndk
Checking out projects:  99% (758/763) platform/tools/tradefederation/contrib^[[1Checking out projects:  99% (762/763), done.

error: Unable to fully sync the tree.
error: Checking out local projects failed.
Failing repos:
prebuilts/ndk

**Comment by rsglobal** [comment]
It looks like ndk repository in .repo folder is corrupted.
Could you try to remove all downloaded data and do repo init && repo sync again?

**Comment by davepo** [comment]
That worked! Thanks!
