### ISSUE TITLE
SIM card usage

### ISSUE THREAD

**Issue by swedneck** [GloDroid/glodroid_manifest#70]
Is it possible to use the SIM card for mobile data and calling? If so, what do i need to do to enable it?

**Comment by rsglobal** [comment]
Hi,
SIM is not yet supported by GloDroid.
Currently you can play with modem only at low level:
https://xnux.eu/devices/feature/modem-pp.html

Supporting it by OS require quectel RIL library at least, and... some additional tuning.

**Comment by swedneck** [comment]
Anything (aside from programming) i could to to help bring SIM support?

**Comment by rsglobal** [comment]
First step I believe is to insert sim card and make a call using echo ATxxx > /devttyUSB2
After you can confirm it is working, next step is to setup audio paths (to modify XML file).

Remaining steps depends on how much experience in Android development do you have.
I also hope to avoid any programming.

Anyway, at first you have to sync with the next branch. Or I can provide you latest integration build tomorrow.

**Comment by swedneck** [comment]
I have 0 experience with android development, but i can certainly test things and report back with results.
How would i run commands? Should i install termux?

**Comment by rsglobal** [comment]
I do not have any experience with this modem. Sorry, but I can't help now.
I will back to enabling modem support when I will have got more free time.
So only thing you can help for now is to "dig": i mean read forums, experiment using Linux distros on PP, etc, and sharing the results.

**Comment by rsglobal** [comment]
Mobile data support: https://xnux.eu/devices/feature/modem-pp-data.html

**Comment by swedneck** [comment]
how would i run commands in android?

**Comment by rsglobal** [comment]
1. Use latest integration build or build the next branch. (It includes modem power manager driver module)
https://github.com/GloDroid/glodroid_manifest/issues/58

Use `adb shell` from your HOST PC to open console
`$ su` to enter superuser mode 
After that you should be able to wakeup the modem.

**Comment by swedneck** [comment]
i will test!

**Comment by rsglobal** [comment]
Android has microcom app, you can try:
```
su
microcom -s 115200 /dev/ttyUSB2
```

**Comment by rsglobal** [comment]
This utility can be used to configure qmi:
https://git.openwrt.org/?p=project/uqmi.git;a=summary

@matviizorin , can you add Android.bp to compile it?
Just like https://github.com/rpetrovski/android-x86-external-uqmi for earlier vesion.

**Comment by matviizorin** [comment]
@rsglobal 
Yes, I can. I'm going to try it after completing the other available activities.

**Comment by rsglobal** [comment]
@bauner is currently WIP on similar activity:
https://github.com/bauner/glodroid_device/commits/ril-gps

**Comment by rsglobal** [comment]
Turn on GPS and listen for data:
```
adb shell
$ su
# echo 1 > /sys/class/modem-power/modem-power/device/powered
# cat /dev/ttyUSB1 &
# echo AT+QGPS=1,30,50,0,2 > /dev/ttyUSB2

You should see GPS data on the screen.

To disable GPS:
# echo AT+QGPSEND > /dev/ttyUSB2
```

**Comment by user293b** [comment]
Is it realistic that it might work in a future release?

**Comment by rsglobal** [comment]
Initial SIM card support is implemented in next branch. It based on Google cuttlefish (emulator) RIL library, therefore isn't 100% compatible with QC25 modem.
