### ISSUE TITLE
Support Chat?

### ISSUE THREAD

**Issue by purringChaos** [GloDroid/glodroid_manifest#73]
Do we have a discord, telegram or IRC where can chat and discuss GloDroid?

**Comment by MaksymPrymierov** [comment]
@purringChaos 
Hello, thanks for your question!
We currently have no chats, but I'm going to create some chats on Telegram and Discord. I'll attach a link with these chats in this issue.

**Comment by purringChaos** [comment]
got it!

**Comment by jholtiv** [comment]
@MaksymPrymierov I prefer Telegram as we can install it from F-Droid

**Comment by swedneck** [comment]
Matrix clients can also be installed from F-Droid, and don't rely on a centralized server.

**Comment by MaksymPrymierov** [comment]
You can already use our [discord chat](https://discord.gg/2z5VUv6). In the future, we may also have chats on other platforms.
