### ISSUE TITLE
[Question] How to update without data lost.

### ISSUE THREAD

**Issue by kev-dev1** [GloDroid/glodroid_manifest#82]
How to update or upgrade the newest build without to lost the Data.

**Comment by rsglobal** [comment]
Hi @kev-dev1 ,

It depends on many factors.
The main is partition layout.
In case new release has the same partition layout as previous, you can just put a comment on `./fastboot format userdata & metadata` lines in `./flash.sh` script and flash.

In theory this should work for v0.3.0 to v0.4.0 transition, but nobody from GD team tested it. So there is a risk for you to lose your data.

To eliminate any risks mobile brands have test department, which tests how will OTA influence user data and system stability  before publishing release.

**Comment by kev-dev1** [comment]
Ok. I will test it in the next Days and see if it is possible to update without data loss

**Comment by kev-dev1** [comment]
The Upgrade from version 0.3.0 to 0.4.0 works.
