### ISSUE TITLE
Pinephone power button not working

### ISSUE THREAD

**Issue by jholtiv** [GloDroid/glodroid_manifest#83]
I am on Pinephone Braveheart edition and using GloDroid v0.4.0. Currently the power button acts only as a back button. The screen does not turn off. Also the screen timeout doesn't turn off the screen as well.

**Comment by rsglobal** [comment]
Hi @jholtiv ,

Sleep mode was disabled due to number of issues. It will be re-enabled as soon as those bugs handled.

**Comment by jholtiv** [comment]
@rsglobal thanks, I wasn't sure what sleep mode was in the changelog. Thanks for the info
