### ISSUE TITLE
[Bug] glodroid 0.1.0 

### ISSUE THREAD

**Issue by hostkit** [GloDroid/glodroid_manifest#9]
After flashing your release sdcard image and load my sdcard. My opi only stuck on Android logo more than 1hours. I don't know to get log.

dd command using libreelec, win32diskimg, and etcher

**Comment by rsglobal** [comment]
I suppose that you can have no heat-sink mounted on your OPI SOC.

We are using 40x40mm heat-sink.

![opi_heatsink](https://user-images.githubusercontent.com/36298915/75059861-7c217480-54e6-11ea-886f-f06c26ef077c.jpg)

**Comment by hostkit** [comment]
My opi mount mini heatsink and fan

**Comment by hostkit** [comment]
> I suppose that you can have no heat-sink mounted on your OPI SOC.
> 
> We are using 40x40mm heat-sink.
> 
> ![opi_heatsink](https://user-images.githubusercontent.com/36298915/75059861-7c217480-54e6-11ea-886f-f06c26ef077c.jpg)

I think your device not plus2e or maybe opiplus2e have different type?
![IMG_20200222_060531](https://user-images.githubusercontent.com/3790389/75078905-7ef98500-5539-11ea-8c50-53b646438561.jpg)

**Comment by rsglobal** [comment]
Yes, you are right, I sent a photo of opi-win (A64 soc). 
We have same size heatsink on opi-plus2e. 

If you are sure that there is no overheat, please check you have got 5V, 2A power supply and cable with low voltage drop.

**Comment by hostkit** [comment]
> Yes, you are right, I sent a photo of opi-win (A64 soc).
> We have same size heatsink on opi-plus2e.
> 
> If you are sure that there is no overheat, please check you have got 5V, 2A power supply and cable with low voltage drop.

I don't know how to check when board offline, but when using libreelec only 45-47.
Adapter? Ok will be check my volt and Amper

**Comment by rsglobal** [comment]
According to my experience the heat-sink on your photo is too small when using OPI's GPU.
Such distributive as armbian does not use GPU hardware acceleration and can work even without heat-sink.
I believe libreelec also.
Soon we plan to switch to kernel 5.6, where thermal driver is available. After that you should experience just performance drop instead of hang in case of overheating.

**Comment by hostkit** [comment]
Do you know, how to remove old heatsink with thermal tape? I want to replace with new heatsink

**Comment by hostkit** [comment]
Ok. I have been successful remove old heatsink. which part must be installed new 40x40 heatsinks? Part 1-5 single heatsink 40x40 without part 6 or 1-5 single heatsink+ part 6 with small heatsink?
![75078905-7ef98500-5539-11ea-8c50-53b646438561~2](https://user-images.githubusercontent.com/3790389/76331267-7a96df80-6321-11ea-9ab8-34ce715768dd.jpg)

**Comment by rsglobal** [comment]
SOC heats mostly. So only 5.

**Comment by rsglobal** [comment]
Try v0.2.0. For me it works even without heatsink:
https://github.com/GloDroid/glodroid_manifest/releases/tag/v0.2.0
