### ISSUE TITLE
Image for Orange PI Plus 2

### ISSUE THREAD

**Issue by BigJacek** [GloDroid/glodroid_manifest#92]
Hello,
Could someone make for me lastest Android 11.0.0 image for Orange PI Plus 2.
I would like to make some tests of this version but unfortunately I don't have resources (lack of RAM) to build it myself.
Regards,
Jacek

**Comment by rsglobal** [comment]
Hi @BigJacek ,

All images are available on Releases page under Assets drop-down list.
https://github.com/GloDroid/glodroid_manifest/releases

In an hour I will publish v0.5.1, so I recommend you to wait.

**Comment by BigJacek** [comment]
Hello Roman,
Thx a lot for the info.

Best regards,
Jacek
