### ISSUE TITLE
Orange Pi PC2 won't boot, bootloop

### ISSUE THREAD

**Issue by DartPower** [GloDroid/glodroid_manifest#98]
Orange Pi PC2 won't boot, bootloop

[dmesg_031020_2.log](https://github.com/GloDroid/glodroid_manifest/files/5333243/dmesg_031020_2.log)
[logcat_opipc2_031020.log](https://github.com/GloDroid/glodroid_manifest/files/5333244/logcat_opipc2_031020.log)
[logcat_opipc2_031020_afterreboot2.log](https://github.com/GloDroid/glodroid_manifest/files/5333245/logcat_opipc2_031020_afterreboot2.log)
[dmesg_031020_1.log](https://github.com/GloDroid/glodroid_manifest/files/5333246/dmesg_031020_1.log)

**Comment by d4rth-v4d3r** [comment]
Were you able to run Android in Orange PI PC 2?

**Comment by DartPower** [comment]
Me don't have a much free disk space, because im cant compile it fully and deploy.
Can you make the release/CI/buildbot?

**Comment by DartPower** [comment]
Soryy, don't seen the Releases. Will check soon

**Comment by DartPower** [comment]
This build (in rel) im already tested (on 2nd October), and this is not working.

**Comment by DartPower** [comment]
Booted. But UI is very laggy...

**Comment by rsglobal** [comment]
closing as stale
